name: 'Contentful App Deploy'
description: 'Custom GitHub Action to deploy frontend apps to Contentful.'
inputs:
  organization-id:
    description: 'The id of the organization'
    required: true
  app-definition-id:
    description: 'The id of the app definition'
    required: true
  access-token:
    description: 'An Access token for the Content Management API'
    required: true
  folder:
    description: 'The folder which is deployed to Contentful App Hosting'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
