name: 'Contentful App Deploy'
description: 'Custom GitHub Action to deploy frontend apps to Contentful.'
inputs:
  organization-id:
    description: 'The id of the organization'
    required: true
  app-definition-id:
    description: 'The id of the app definition'
    required: true
  access-token:
    description: 'A personal access token for the Content Management API'
    required: true
  folder:
    description: 'The folder which is deployed to Contentful App Hosting'
    required: true
  comment:
    description: 'A comment which will be associated with the created AppBundle. Can be used to differentiate bundles.'
    required: false
  allow-tracking:
    description: 'The flag to allow tracking of the app-definition-id, branch deployed'
    required: false
    default: true
runs:
  using: 'node20'
  main: 'dist/index.js'
