name: 'Contentful App Deploy'
description: 'Custom GitHub Action to deploy frontend apps to Contentful.'
inputs:
  organization-id:
    description: ''
    required: true
  app-definition-id:
    description: ''
    required: true
  access-token:
    description: ''
    required: true
  folder:
    description: ''
    required: true
outputs:
  result:
    description: 'Successfully Deployed or not'
runs:
  using: 'node16'
  main: 'build.js'
