name: 'Contentful App Deploy'
description: 'Custom GitHub Action to deploy frontend apps to Contentful'
inputs:
  organization-id:
    description: ''
    required: true
    default: ''
  app-definition-id:
    description: ''
    required: true
    default: ''
  access-token:
    description: ''
    required: true
    default: ''
  folder:
    description: ''
    required: true
    default: ''
outputs:
  result:
    description: 'Successfully Deployed or not'
runs:
  using: 'node16'
  main: 'build.js'