on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Job to build custom GitHub action
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          organization-id: ${{ secrets.ORGANIZATION_ID }}
          app-definition-id: ${{ secrets.APP_DEFINITION_ID }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          folder: ${{ secrets.FOLDER }}
