on: [push]

jobs:
  deploy_app_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Job to build custom GitHub action
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm run format-check
      - run: npm run lint
      - run: npm ci
      - run: npm run build
